name: pos

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    command: --default-time-zone=+00:00
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "7379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
